global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-1:8080
          - api-2:8080
        labels:
          service: api

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:9091
        labels:
          service: worker

  - job_name: outbox-relay
    metrics_path: /metrics
    static_configs:
      - targets:
          - outbox-relay:9092
        labels:
          service: outbox-relay
